app/blog/forms.py
from ..main.forms import RenderForm
from wtforms import SubmitField, StringField, TextAreaField, SelectField, FileField
from wtforms.validators import DataRequired, Length
from ..models import Category
from flask_ckeditor import CKEditorField


# 发表文章
class PostForm(RenderForm):
    image = FileField()
    title = StringField(label='标题', validators=[DataRequired(), Length(1, 255)])
    summary = StringField(label='概述')
    category = SelectField(label="文章分类", coerce=int)
    sub_category = SelectField(label="二级分类", coerce=int)
    body = CKEditorField(label="正文", validators=[DataRequired()])
    submit = SubmitField(label='提交')

    # 添加 分类选择表单 category 的值
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.category.choices = [(0, '')]  # 给表单设置初始空值，以触发表单onchange事件
        self.sub_category.choices = [(0, '')]
        for category in Category.query.order_by(Category.id).all():
            # 初始化时将一级分类和二级分类区分开，分别给两个字段初始化
            if category.parent is None:
                self.category.choices.append((category.id, category.name))
            else:
                self.sub_category.choices.append((category.id, category.name))



# 文章修改
class PostEditForm(RenderForm):
    image = FileField()
    title = StringField(label='标题', validators=[DataRequired(), Length(1, 255)])
    summary = StringField(label='概述')
    category = SelectField(label="文章分类", coerce=int)
    sub_category = SelectField(label="二级分类", coerce=int)
    body = CKEditorField(label="正文", validators=[DataRequired()])
    # body = TextAreaField(label="正文", validators=[DataRequired()],
    #                      render_kw={'data-provide': "markdown", 'rows': '10',
    #                                 "placeholder": "文章正文(支持MarkDown)",
    #                                 'class': "form-control form-control-md g-color-black g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--focus g-resize-none rounded-3 g-pa-15"})
    submit = SubmitField(label='提交')

    # 添加 分类选择表单 category 的值
    def __init__(self, *args, **kwargs):
        super(PostEditForm, self).__init__(*args, **kwargs)
        self.category.choices = [(0, '')]  # 给表单设置初始空值，以触发表单onchange事件
        self.sub_category.choices = [(0, '')]
        for category in Category.query.order_by(Category.id).all():
            # 初始化时将一级分类和二级分类区分开，分别给两个字段初始化
            if category.parent is None:
                self.category.choices.append((category.id, category.name))
            else:
                self.sub_category.choices.append((category.id, category.name))


# 发表评论&回复
class CommentForm(RenderForm):
    body = TextAreaField(label="正文", validators=[DataRequired()],
                         render_kw={'data-provide': "markdown", 'rows': '6',
                                    "placeholder": "发表评论(支持MarkDown)",
                                    'class': "form-control form-control-md g-color-black g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--focus g-resize-none rounded-3 g-pa-15"})
    parent = StringField(label="被回复评论的id",
                         render_kw={'readonly': '', 'class': 'g-pos-abs g-top-0 invisible'})
    submit_comment = SubmitField(label='提交')


# 修改评论
class CommentEditForm(RenderForm):
    body = TextAreaField(label="正文", validators=[DataRequired()],
                         render_kw={'data-provide': "markdown", 'rows': '6',
                                    'class': "form-control form-control-md g-color-black g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--focus g-resize-none rounded-3 g-pa-15"})
    id = StringField(label="自己的id",
                     render_kw={'readonly': '', 'class': 'g-pos-abs g-top-0 invisible'})
    submit_edit_comment = SubmitField(label='提交')


# 收藏文章
class LikePostForm(RenderForm):
    submit_like_post = SubmitField()

# 取消收藏
class DislikePostForm(RenderForm):
    submit_dislike_post = SubmitField()

app/blog/__init__.py
from flask import Blueprint

blog = Blueprint('blog', __name__)

from . import views
from ..models import Permission


# 添加应用上下文处理器，使得渲染时，模板中能够直接调用Permission类而无需导入
@blog.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

app/blog/views.py
from . import blog
from app import db, post_img
from ..models import Post, Permission, Category, Comment
from flask import render_template, abort, flash, redirect, url_for, request, jsonify, send_from_directory, current_app
from flask_login import current_user, login_required
from .forms import PostEditForm, CommentForm, CommentEditForm, LikePostForm, DislikePostForm, PostForm
from app.decorators import permission_require
from flask_uploads import UploadNotAllowed
from flask_ckeditor import upload_success, upload_fail
import os
from sqlalchemy import extract
# import flask_whooshalchemyplus
from config import basedir

# 博客地址
@blog.route('/post/<int:id>', methods=['GET', 'POST'])
def post(id):
    form = CommentForm()  # 用于发表评论的表单
    form2 = CommentEditForm()  # 用于修改评论的表单
    form3 = LikePostForm()  # 用于收藏文章
    form4 = DislikePostForm()  # 用于取消收藏
    type_flag = 'CommentForm'
    post = Post.query.get_or_404(id)
    comments = Comment.query.filter_by(post_id=post.id).order_by(Comment.timestamp).all()
    user = current_user._get_current_object()
    # 打开后浏览数+1
    post.views += 1
    db.session.add(post)
    db.session.commit()
    # 文章评论
    if form.validate_on_submit() and form.submit_comment.data:
        comment = Comment(
            body=form.body.data,
            post=post,
            author=current_user._get_current_object(),
            parent=Comment.query.get(form.parent.data)
        )
        db.session.add(comment)
        db.session.commit()
        flash("您的评论已发布！")
        return redirect(url_for('blog.post', id=post.id))
    # 修改评论
    if form2.validate_on_submit() and form2.submit_edit_comment.data:
        comment = Comment.query.get_or_404(form2.id.data)
        comment.body = form2.body.data
        db.session.add(comment)
        db.session.commit()
        flash('已修改评论！')
        return redirect(url_for('blog.post', id=post.id))
    # 收藏文章
    if form3.validate_on_submit() and form3.submit_like_post.data:
        user.like(post)
        db.session.commit()
        flash('已收藏文章！', 'success')
        return redirect(url_for('blog.post', id=post.id))
    # 取消收藏
    if form4.validate_on_submit() and form4.submit_dislike_post.data:
        user.dislike(post)
        db.session.commit()
        flash('已取消收藏！')
        return redirect(url_for('blog.post', id=post.id))
    return render_template('blog/post.html', post=post, comments=comments, form=form,
                           form2=form2, form3=form3, form4=form4, type_flag=type_flag)


# 发布博客
@blog.route('/new-post', methods=['GET', 'POST'])
@login_required
def new_post():
    if not current_user.can(Permission.ADMIN):
        abort(403)
    post = Post()
    form = PostForm()
    # 处理文章头图
    if request.method == 'POST' and 'image' in request.files:
        try:
            filename = post_img.save(request.files['image'])
        except UploadNotAllowed:
            pass
        else:
            post.image = url_for("static", filename='img/upload/post_img/' + filename)
    # 处理二级表单
    if request.method == 'POST' and not form.submit.data:
        data = request.get_json()
        name = data['name']
        category = Category.query.filter_by(name=name).first()
        sub_categories = {category.id: category.name for category in
                          Category.query.filter_by(parent_id=category.id).all()}
        return jsonify(sub_categories)
    if form.validate_on_submit():
        post.author_id = current_user.id
        post.title = form.title.data
        # 如果没有输入一级分类，就设置成默认分类（未分类）
        if not form.category.data:
            post.category = Category.query.filter_by(default=True).first()
        # 如果输入了一级分类和二级分类，就设置成二级分类
        elif form.sub_category.data:
            post.category = Category.query.get(form.sub_category.data)
        # 如果只输入了一级分类， 就设置成一级分类
        else:
            post.category = Category.query.get(form.category.data)
        post.summary = form.summary.data
        post.body = form.body.data
        db.session.add(post)
        db.session.commit()
        # flask_whooshalchemyplus.index_one_model(Post)  # 提交文章后 创建搜索索引
        flash('博客发表')
        return redirect(url_for('.post', id=post.id))
    return render_template("blog/new_post.html", form=form)


# 编辑博客
@blog.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    post = Post.query.get_or_404(id)
    if current_user != post.author and not current_user.can(Permission.ADMIN):
        abort(403)
    form = PostEditForm()
    # 处理文章头图
    if request.method == 'POST' and 'image' in request.files:
        try:
            filename = post_img.save(request.files['image'])
        except UploadNotAllowed:
            pass
        else:
            # 如果用户已经有头像了，就删除原先头像文件
            post_img_path = os.path.join(basedir, 'app', post.image[1:])  # user.avatar 第一个字符‘/’会使得join 不能正确拼接路径，需要去掉
            if os.path.exists(post_img_path):
                os.remove(post_img_path)
            post.image = url_for("static", filename='img/upload/post_img/' + filename)
    # 处理二级表单
    if request.method == 'POST' and not form.submit.data:
        data = request.get_json()
        name = data['name']
        category = Category.query.filter_by(name=name).first()
        sub_categories = {category.id: category.name for category in
                          Category.query.filter_by(parent_id=category.id).all()}
        return jsonify(sub_categories)
    if form.validate_on_submit():
        post.title = form.title.data
        # 如果没有输入一级分类，就设置成默认分类（未分类）
        if not form.category.data:
            post.category = Category.query.filter_by(default=True).first()
        # 如果输入了一级分类和二级分类，就设置成二级分类
        elif form.sub_category.data:
            post.category = Category.query.get(form.sub_category.data)
        # 如果只输入了一级分类， 就设置成一级分类
        else:
            post.category = Category.query.get(form.category.data)
        post.summary = form.summary.data
        post.body = form.body.data
        db.session.add(post)
        db.session.commit()
        # flask_whooshalchemyplus.index_one_model(Post)  # 修改文章后 创建搜索索引
        flash('博客已修改成功')
        return redirect(url_for('.post', id=post.id))
    form.title.data = post.title
    form.category.data = post.category_id
    form.summary.data = post.summary
    form.body.data = post.body
    return render_template("blog/edit_post.html", form=form, post=post)


# 博客分类页面
@blog.route('/post/<category_name>')
def category_posts(category_name):
    category = Category.query.filter_by(name=category_name).first_or_404()
    page = request.args.get('page', 1, type=int)
    sub_categories = Category.query.filter_by(parent_id=category.id).all()  # 查询二级分类
    categories_list = [sub_category.id for sub_category in sub_categories]  # 二级子分类id列表
    categories_list.append(category.id)  # 分类列表中添加自己(一级分类)
    # 一级分类 并且有子分类
    if not category.parent_id and sub_categories:
        pagination = Post.query.filter(
            Post.category_id.in_(categories_list)).order_by(
            Post.timestamp.desc()).paginate(
            page, per_page=9, error_out=False)
    # 一级分类 但没有子分类 ； 二级分类
    else:
        pagination = Post.query.filter_by(category_id=category.id).order_by(Post.timestamp.desc()).paginate(
            page, per_page=9, error_out=False)
    posts = pagination.items
    no_post_flag = False
    if pagination.total == 0:
        flash('抱歉，该分类下暂时没有文章。', 'warning')
        no_post_flag = True
    return render_template('blog/category_post.html',
                           category=category, posts=posts, page=page, pagination=pagination, no_post_flag=no_post_flag)


# 博客时间归档页面(月)
@blog.route('/<int:year>/<int:month>')
def archive_month(year, month):
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.filter(extract('year', Post.timestamp) == year,
                                   extract('month', Post.timestamp) == month
                                   ).order_by(Post.timestamp.desc()).paginate(
        page, per_page=9, error_out=False)
    posts = pagination.items
    return render_template('blog/archives_month.html', posts=posts, page=page, pagination=pagination, year=year, month=month)


# 博客时间归档页面(年)
@blog.route('/<int:year>')
def archive_year(year):
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.filter(extract('year', Post.timestamp) == year).order_by(Post.timestamp.desc()).paginate(
        page, per_page=9, error_out=False)
    posts = pagination.items
    return render_template('blog/archives_year.html', posts=posts, page=page, pagination=pagination, year=year)


# 博客About页面
@blog.route('/about')
def about():
    return render_template('blog/about.html')

# 管理评论
@blog.route('/moderate/<int:id>')
@login_required
@permission_require(Permission.MODERATE)
def moderate(id):
    page = request.args.get('page', 1, type=int)
    post = Post.query.get_or_404(id)
    pagination = Comment.query.filter_by(post_id=id).order_by(Comment.timestamp.desc()).paginate(
        page, per_page=10, error_out=False)
    comments = pagination.items
    return render_template('blog/comment_moderate.html', post=post, comments=comments, pagination=pagination, page=page)


# 解除屏蔽
@blog.route('/moderate/enable/<int:id>')
@login_required
@permission_require(Permission.MODERATE)
def moderate_enable(id):
    comment = Comment.query.get_or_404(id)
    comment.disable = False
    db.session.add(comment)
    db.session.commit()
    return redirect(url_for('blog.moderate', id=comment.post_id, page=request.args.get('page', 1, type=int)))


# 屏蔽评论
@blog.route('/moderate/disable/<int:id>')
@login_required
@permission_require(Permission.MODERATE)
def moderate_disable(id):
    comment = Comment.query.get_or_404(id)
    comment.disable = True
    db.session.add(comment)
    db.session.commit()
    return redirect(url_for('blog.moderate', id=comment.post_id, page=request.args.get('page', 1, type=int)))


# 文章内图片
@blog.route('/files/<path:filename>')
def uploaded_files(filename):

app/templates/blog/_post_grid.html
<div class="grid row" data-masonry='{ "itemSelector": ".grid-item", "columnWidth": 200}'>
    {% for post in posts %}
        <div class="gird-item col-sm-6 col-lg-4 g-mb-4">
            <article class="u-shadow-v21 u-shadow-v21--hover g-transition-0_3 mb-5">
                {% if post.image %}
                <img class="img-fluid" src="{{ post.image }}" alt="">
                {% endif %}
                <div class="g-bg-white g-pa-30 g-rounded-bottom-5">
                    <ul class="list-inline g-font-size-12 g-color-gray-dark-v4 ">
                        <li class="list-inline-item g-font-weight-600 g-color-blue mr-0">{{ post.author.username }}</li>
                        <li class="list-inline-item mx-2">发表于</li>
                        <li class="list-inline-item  ">{{ moment(post.timestamp).format('l') }}</li>
                    </ul>
                    <div class="">
                        <a class="g-font-size-22 g-color-gray-dark-v2 g-color-primary--hover text-decoration-none g-transition-0_3 g-cursor-pointer "
                        href="{{ url_for('blog.post', id=post.id) }}"><strong>{{ post.title }}</strong></a>
                        <p class="g-color-gray-dark-v4">{{ post.summary }}</p>
                        <ul class="list-inline">
                            {% if post.category.parent %}
                            <li class="list-inline-item">
                                <a class="g-color-cyan g-bg-cyan-opacity-0_1 g-bg-cyan--hover g-color-white--hover g-rounded-50 g-py-4 g-px-15 u-tags-v1"
                                   href="{{ url_for('blog.category_posts', category_name=post.category.parent.name) }}">{{ post.category.parent.name }}</a>
                            </li>
                            {% endif %}
                            <li class="list-inline-item">
                                <a class="g-color-lightred g-bg-lightred-opacity-0_1 g-bg-lightred--hover g-color-white--hover g-rounded-50 g-py-4 g-px-15 u-tags-v1"
                                   href="{{ url_for('blog.category_posts', category_name=post.category.name) }}">
                                    {{ post.category.name }}</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </article>
        </div>
    {% endfor %}
</div>

app/templates/blog/archives_month.html
{% extends "base.html" %}
{% from "_macros.html" import pagination_widget %}

{% block title %}Potato Cookbook - 归档 {{ year }}年{{ month }}月{% endblock %}

{% block content %}
<div class="g-bg-gray-light-v5">
    <div class="container g-py-50">
    {% include "blog/_post_grid.html" %}
    {{ pagination_widget(pagination, 'blog.archive_month', year=year, month=month) }}
    </div>
</div>
{% endblock %}

app/templates/blog/archives_year.html
{% extends "base.html" %}
{% from "_macros.html" import pagination_widget %}

{% block title %}Potato Cookbook - 归档 {{ year }}年{% endblock %}

{% block content %}
<div class="g-bg-gray-light-v5">
    <div class="container g-py-50">
    {% include "blog/_post_grid.html" %}
    {{ pagination_widget(pagination, 'blog.archive_year', year=year) }}
    </div>
</div>
{% endblock %}

app/templates/blog/category_post.html
{% extends "base.html" %}
{% from "_macros.html" import pagination_widget %}

{% block title %}Potato Cookbook - {{ category.name }}{% endblock %}

{% block content %}
<div class="g-bg-gray-light-v5">
    <div class="container g-py-50">
    {% if no_post_flag == True %}
    <h3 class="text-center"> 抱歉，该分类下暂时没有文章。 </h3>
    {% endif %}
        <div class="grid row" data-masonry='{ "itemSelector": ".grid-item", "columnWidth": 200}'>
            {% for post in posts %}
                <div class="gird-item col-sm-6 col-lg-4 g-mb-4">
                    <article class="u-shadow-v21 u-shadow-v21--hover g-transition-0_3 mb-5">
                        {% if post.image %}
                        <img class="img-fluid" src="{{ post.image }}" alt="">
                        {% endif %}
                        <div class="g-bg-white g-pa-30 g-rounded-bottom-5">
                            <ul class="list-inline g-font-size-12 g-color-gray-dark-v4 ">
                                <li class="list-inline-item g-font-weight-600 g-color-blue mr-0">{{ post.author.username }}</li>
                                <li class="list-inline-item mx-2">发表于</li>
                                <li class="list-inline-item  ">{{ moment(post.timestamp).format('l') }}</li>
                            </ul>
                            <div class="">
                                <a class="g-font-size-22 g-color-gray-dark-v2 g-color-primary--hover text-decoration-none g-transition-0_3 g-cursor-pointer "
                                href="{{ url_for('blog.post', id=post.id) }}"><strong>{{ post.title }}</strong></a>
                                <p class="g-color-gray-dark-v4">{{ post.summary }}</p>
                                <ul class="list-inline">
                                    {% if post.category.parent %}
                                    <li class="list-inline-item">
                                        <a class="g-color-cyan g-bg-cyan-opacity-0_1 g-bg-cyan--hover g-color-white--hover g-rounded-50 g-py-4 g-px-15 u-tags-v1"
                                           href="{{ url_for('blog.category_posts', category_name=post.category.parent.name) }}">{{ post.category.parent.name }}</a>
                                    </li>
                                    {% endif %}
                                    <li class="list-inline-item">
                                        <a class="g-color-lightred g-bg-lightred-opacity-0_1 g-bg-lightred--hover g-color-white--hover g-rounded-50 g-py-4 g-px-15 u-tags-v1"
                                           href="{{ url_for('blog.category_posts', category_name=post.category.name) }}">
                                            {{ post.category.name }}</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </article>
                </div>
            {% endfor %}
        </div>
    {{ pagination_widget(pagination, 'blog.category_posts', category_name=category.name) }}
    </div>
</div>
{% endblock %}

app/templates/blog/comment_moderate.html
{% extends "base.html" %}
{% from "_macros.html" import pagination_widget %}

{% block title %}Potato Cookbook - 管理评论{% endblock %}

{% block articles %}
    <div class="card-body g-pt-10 px-0">
        <h1 class="text-dark g-font-weight-600 "><strange>评论管理</strange>&emsp;--&emsp;<<{{ post.title }}>>
            <a href="{{ url_for('blog.post', id=post.id) }}" class="btn d-inline-block mt-3 btn-success pull-right">返回文章</a>
        </h1>
        <hr>
    </div>
    {% set moderate=True %}
    {% include "_comment.html" %}
    <div>
    {{ pagination_widget(pagination, 'blog.moderate', id=post.id) }}
    </div>
{% endblock %}

app/templates/blog/edit_post.html
{% extends "blog/new_post.html" %}

{% block title %}Potato Cookbook - {{ post.title }} {% endblock %}

{% block category_url %}
    <script>
        let category_url = "{{ url_for('blog.edit', id=post.id) }}";
        {#let csrf = "{{ csrf_token() }}";#}
    </script>
    <script src="{{ url_for('static', filename='js/custom.js') }}" charset="UTF-8"></script>
{#    文件表单选择文件后更改名字 #}
    <script>
        $('.custom-file-input').on('change', function() {
            let fileName = $(this).val().split('\\').pop();
            $(this).next('.custom-file-label').addClass("selected").html(fileName);
        });
    </script>
{% endblock %}

app/templates/blog/new_post.html
{% extends "base.html" %}

{% block title %}Potato Cookbook - 发表博客 {% endblock %}


{% block page_content %}
<div class="col-12">
    <div class="u-heading-v3-1 g-mb-30">
    <h4 class="u-heading-v3__title g-color-primary g-brd-primary">编辑文章</h4>
    </div>
    <div class="mb-5">
    {% if current_user.can(Permission.WRITE) %}
        <form method="post" enctype=multipart/form-data>
            {{ form.hidden_tag() }}
    {#            post image #}
            <div class="form-row mb-2">
                 <p class="g-font-size-16 g-font-weight-600 g-px-5 g-mb-7">文章头图</p>
                <div class="col-12 mb-2">
                    <div class="input-group">
                        <div class="custom-file">
                            <input type=file class="custom-file-input" id="upload" name=image >
                            <label class="custom-file-label" for="upload" data-browse="浏览文件">选择文件</label>
                        </div>
                    </div>
                </div>
            </div>
    {#            post title & category #}
            <div class="form-row mb-2">
                <div class="col-md-6 mb-2">
                    {{ form.title.label(class="g-font-size-16 g-font-weight-600 ") }}
                    {{ form.title(class="form-control", placeholder="标题") }}
                </div>
                <div class="col-md-3 mb-2">
                    {{ form.category.label(class="g-font-size-16 g-font-weight-600") }}
                    {{ form.category(class="form-control", placeholder="文章分类", onchange="Select('category', '#sub_category', category_url)") }}
                </div>
                <div class="col-md-3 mb-2">
                    {{ form.sub_category.label(class="g-font-size-16 g-font-weight-600") }}
                    {{ form.sub_category(class="form-control", placeholder="二级分类") }}
                </div>
            </div>
    {#            post summary #}
            <div class="form-row mb-2">
                <div class="col-12 mb-2">
                    {{ form.summary.label(class="g-font-size-16 g-font-weight-600 ") }}
                    {{ form.summary(class="form-control", placeholder="概述") }}
                </div>
            </div>
    {#            post body #}
            <div class="mb-4">{{ form.body() }}</div>
            <div class="text-center" >{{ form.submit(class="btn btn-lg u-btn-primary") }}</div>
        {#        initialize ckeditor #}
        {{ ckeditor.load() }}
        {{ ckeditor.config(name='body') }}
        </form>
    {% endif %}
    </div>
</div>
{% endblock page_content %}


{% block scripts %}
{{ super() }}
    {% block category_url %}
    <script>
        let category_url = "{{ url_for('blog.new_post') }}";
        {#let csrf = "{{ csrf_token() }}";#}
    </script>
    <script src="{{ url_for('static', filename='js/custom.js') }}" charset="UTF-8"></script>
{#    文件表单选择文件后更改名字 #}
    <script>
        $('.custom-file-input').on('change', function() {
            let fileName = $(this).val().split('\\').pop();
            $(this).next('.custom-file-label').addClass("selected").html(fileName);
        });
    </script>
    {% endblock %}
{% endblock %}

app/templates/blog/post.html
{% extends "base.html" %}

{% block title %}Potato Cookbook - {{ post.title }} {% endblock %}

{% block articles %}
<div class="mb-5">
{# header #}
    <div class="card-body g-pt-10 px-0">
        {# edit button #}
        {% if current_user == post.author or current_user.can(Permission.ADMIN) %}
            <a class="d-block btn btn-xs u-btn-deeporange float-right px-3 g-mt-25" href="{{ url_for('blog.edit', id=post.id) }}">编辑文章</a>
        {% endif %}
        {# title #}
        <h1 class="text-dark g-font-weight-600 g-color-primary">{{ post.title }}</h1>
        {# post info #}
        <ul class="list-inline d-sm-flex g-color-gray-dark-v4 mb-0">
            <li class="list-inline-item">
                <span class="btn btn-xs u-btn-outline-red g-mr-10">原创</span>
            </li>
            <li class="list-inline-item">
                <a href="#" class="u-link-v5 g-color-gray-dark-v4 g-color-primary--hover">{{ post.author.username }}</a>
            </li>
            <li class="list-inline-item g-mx-10">/</li>
            <li class="list-inline-item">
                <i class="fa fa-clock-o"></i>
                <span>{{ moment(post.timestamp).format('YYYY年MM月DD日 HH:mm') }}</span>
            </li>
            <li class="list-inline-item g-mx-10">/</li>
            <li class="list-inline-item g-mx-10">
                <i class="fa fa-comment-o"></i>
                <span>{{ post.comments.count() }}</span>
            </li>
            <li class="list-inline-item ml-auto">
                <i class="fa fa-eye"></i>
                <span>&nbsp;{{ post.views }}</span>
            </li>
        </ul>
    </div>
    <hr class="g-color-gray-dark-v4 mt-2">
{# post body #}
    <div>
        {#    header-image  #}
        {#    <img src="#" class="card-img-top" alt="">#}
        {# post summary #}
        <p class="card-text mb-0"><strong class="g-color-primary g-mr-5">概要：</strong>{{ post.summary }}</p>
        <div class="u-divider u-divider-db-dashed u-divider-center g-brd-gray-light-v2 g-my-50">
            <i class="fa fa-arrow-down u-divider__icon u-divider__icon--indented g-bg-gray-light-v4 g-color-gray-light-v1 rounded-circle"></i>
        </div>
        <div class="markdown-body">
            {% if post.body_html %}
                {{ post.body_html | safe }}
            {% else %}
                {{ post.body }}
            {% endif %}
        </div>
    </div>
{# footer #}
    <div class="g-mt-15 g-mb-30 d-flex justify-content-between">
        <h6 class="g-color-gray-dark-v1 g-mb-15">
            <strong class="g-color-primary g-mr-15">分类:</strong>
            <a class="btn btn-sm btn-outline-primary" href="{{ url_for('blog.category_posts', category_name=post.category.name) }}">{{ post.category.name }}</a>
        </h6>
        {% if current_user.is_authenticated %}
            {% if not current_user.liked(post) %}
                <form method="post" action="{{ url_for('blog.post', id=post.id) }}">
                    {{ form3.hidden_tag() }}
                    {{ form3.submit_like_post(class="btn g-brd-gray-light-v3 g-color-red--hover g-brd-red--hover g-rounded-50 g-pa-7-16 ", value="收藏文章") }}
                </form>
            {% else %}
                <form method="post" action="{{ url_for('blog.post', id=post.id) }}">
                    {{ form4.hidden_tag() }}
                    {{ form4.submit_dislike_post(class="btn g-brd-gray-light-v3 g-color-yellow--hover g-brd-yellow--hover g-rounded-50 g-pa-7-16", value='取消收藏') }}
                </form>
            {% endif %}
        {% endif %}
    </div>
{#    social-share #}
    <div class="u-heading-v1-5 g-brd-gray-light-v2 text-center">
        <h2 class="u-heading-v1__title g-bg-white pl-15">
            <div class="social-share"  data-disabled="google,facebook,qzone,linkedin,diandian,tencent"></div>
        </h2>
    </div>
</div>
{# comment #}
<div class="u-heading-v3-1 g-mb-30">
<h4 class="u-heading-v3__title g-color-primary g-brd-primary">文章评论</h4>
{# comment moderation #}
{% if current_user.can(Permission.MODERATE) %}
    <a href="{{ url_for('blog.moderate', id=post.id) }}" class="btn btn-sm btn-outline-danger pull-right">管理评论</a>
{% endif %}
</div>
{% include "_comment.html" %}
{# comment editor #}
<div class="u-heading-v3-1 g-mb-30">
<h4 class="u-heading-v3__title g-color-primary g-brd-primary">发表评论</h4>
</div>
{% include "_comment_editor.html" %}
{% endblock articles %}