app/user/forms.py
from ..auth.forms import RenderForm
from wtforms import StringField, BooleanField, TextAreaField, SubmitField, SelectField, FileField, ValidationError
from wtforms.validators import Length, DataRequired, Email, Regexp
from ..models import Role, User


# 编辑个人资料表单
class EditProfileForm(RenderForm):
    name = StringField(validators=[Length(0, 64)])
    gender = SelectField(coerce=int, choices=[(1, '男'), (0, '女')])
    location = StringField(validators=[Length(0, 64)])
    about_me = TextAreaField()
    submit = SubmitField()


# 管理员用编辑资料表单
class EditProfileAdminForm(RenderForm):
    email = StringField(validators=[DataRequired(), Length(1, 64), Email(message="请输入有效的邮箱")])
    username = StringField(validators=[DataRequired(), Length(1, 64),
                                       Regexp('^[a-zA-Z][a-zA-Z0-9_.]*$', 0, "用户名只能使用数字字母和下划线~")])
    confirmed = BooleanField()
    role = SelectField(coerce=int)
    name = StringField(validators=[Length(0, 64)])
    gender = SelectField(coerce=int, choices=[(1, '男'), (0, '女')])
    location = StringField(validators=[Length(0, 64)])
    about_me = TextAreaField()
    submit = SubmitField()

    # 添加 用户组选择表单role 的值
    def __init__(self, user, *args, **kwargs):
        super(EditProfileAdminForm, self).__init__(*args, **kwargs)
        self.role.choices = [(role.id, role.name) for role in Role.query.order_by(Role.name).all()]
        self.user = user  # 表单接收用户作为参数，以便在自定义的验证方法如validate_email中能够使用变量user

    def validate_email(self, field):
        if field.data != self.user.email and User.query.filter_by(email=field.data).first():
            raise ValidationError('该邮箱已被注册')

    def validate_username(self, field):
        if field.data != self.user.username and User.query.filter_by(username=field.data).first():
            raise ValidationError('该用户名已被使用')

app/user/__init__.py
from flask import Blueprint

user_page = Blueprint('user_page', __name__)

from . import views

app/user/views.py
from . import user_page
import os
from flask import render_template, redirect, url_for, flash, request, current_app
from flask_login import login_required, current_user
from flask_uploads import UploadNotAllowed
from ..models import User, Permission, Role, Comment, Like
from .forms import EditProfileForm, EditProfileAdminForm
from app import db, avatars
from ..decorators import admin_required
from config import basedir

# 个人主页
@user_page.route('/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    # 当试图进入他人的个人主页时，重定向到首页
    if not current_user.can(Permission.ADMIN) and current_user.id != user.id:
        flash("不可以偷看别人的主页哦~")
        return redirect(url_for('main.index'))
    return render_template('user/user_page.html', user=user)

# 编辑个人资料
@user_page.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    user = current_user._get_current_object()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.gender = form.gender.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        db.session.add(current_user._get_current_object())
        db.session.commit()
        flash('资料已更新！')
        return redirect(url_for('user_page.user', username=current_user.username))
    form.name.data = current_user.name if current_user.name else ''
    form.gender.data = current_user.gender
    form.location.data = current_user.location if current_user.location is not None else ''
    form.about_me.data = current_user.about_me if current_user.about_me is not None else ''
    return render_template('user/edit_profile.html', form=form, user=user)

# 编辑个人资料（管理员）
@user_page.route('/edit-profile/<int:id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(id):
    user = User.query.get_or_404(id)
    form = EditProfileAdminForm(user=user)
    if form.validate_on_submit():
        user.email = form.email.data
        user.username = form.username.data
        user.confirmed = form.confirmed.data
        user.role = Role.query.get(form.role.data)
        user.name = form.name.data
        user.gender = form.gender.data
        user.location = form.location.data
        user.about_me = form.about_me.data
        db.session.add(user)
        db.session.commit()
        flash('资料已更新！')
        return redirect(url_for('.user', username=user.username))
    form.username.data = user.username
    form.email.data = user.email
    form.confirmed.data = user.confirmed
    form.role.data = user.role_id
    form.name.data = user.name
    form.gender.data = user.gender
    form.location.data = user.location
    form.about_me.data = user.about_me
    return render_template('user/edit_profile.html', form=form, user=user)


# 上传头像页面
@user_page.route('/upload-avatar', methods=['GET', 'POST'])
@login_required
def upload_avatar():
    user = current_user._get_current_object()
    if request.method == 'POST' and 'avatar' in request.files:
        try:
            filename = avatars.save(request.files['avatar'])
        except UploadNotAllowed:
            flash('请选择要上传的文件！')
        else:
            # 如果用户已经有头像了，就删除原先头像文件
            avatar_path = os.path.join(basedir, 'app', user.avatar[1:])  # user.avatar 第一个字符‘/’会使得join 不能正确拼接路径，需要去掉
            if os.path.exists(avatar_path) and user.avatar != '/static/img/avatar/akkarin.jpg':
                os.remove(avatar_path)
            user.avatar = url_for('static', filename='img/upload/avatar/'+filename)
            db.session.add(user)
            db.session.commit()
            flash('头像已更新')
            return redirect(url_for('user_page.user', username=user.username))
    return render_template('user/upload_avatar.html', user=user)

# 管理个人评论
@user_page.route('/my-comments')
@login_required
def my_comments():
    user = current_user._get_current_object()
    page = request.args.get('page', 1, type=int)
    pagination = user.comments.order_by(Comment.timestamp.desc()).paginate(
        page, per_page=5, error_out=False)
    comments = pagination.items
    return render_template('user/my_comments.html', user=user, page=page, pagination=pagination, comments=comments)


# 管理收藏文章
@user_page.route('/my-likes')
@login_required
def my_likes():
    user = current_user._get_current_object()
    page = request.args.get('page', 1, type=int)
    pagination = user.likes.order_by(Like.timestamp.desc()).paginate(
        page, per_page=5, error_out=False)
    likes = pagination.items
    return render_template('user/my_likes.html', user=user, page=page, pagination=pagination, likes=likes)

app/templates/user/edit_profile.html
{% extends "user/user_page.html" %}
{% from 'custom_macros.html' import render_field %}

{% block title %}{{ user.username }} - 编辑资料{% endblock %}

{% block user_page_right_side %}
    <div class="col-md-8 g-mb-50 ">
                <div class="border g-bg-white g-brd-gray-light-v4 rounded" style="min-height: 440px">
                    <section class="g-color-gray-dark-v4">
                        <header class="text-center mt-4 mb-3"><h3>编辑资料</h3></header>
                        <hr class="mx-5">
                        <form method="post">
                            {{ form.hidden_tag()  }}
                        {# 用户名 & 邮箱 #}
                            {% if current_user.is_administrator() %}
                                <div class="row mx-5">
                                    <div class="col-sm-6 d-flex align-items-center mb-3"><p class="my-0">用户名：</p>{{ render_field(form.username) }}</div>
                                    <div class="col-sm-6 d-flex align-items-center mb-3"><p class="my-0">邮箱：</p>{{  render_field(form.email) }}</div>
                                </div>
                            {% else %}
                                <div class="row mx-5">
                                    <div class="col-sm-6"><p>用户名：{{ user.username }}</p></div>
                                    <div class="col-sm-6"><p>邮箱：{{ user.email }}</p></div>
                                </div>
                            {% endif %}
                        {# 用户组 & 邮箱认证 #}
                            {% if current_user.is_administrator() %}
                                <div class="row mx-5">
                                    <div class="col-sm-6 d-flex align-items-center mb-3"><p class="my-0">用户组：</p>{{ form.role(class='form-control form-control-sm g-font-size-13 g-max-width-60x') }}</div>
                                    <div class="col-sm-6 d-flex align-items-center mb-3">
                                        <p class="my-0">邮箱已认证：</p>
                                            <label class="form-check-inline u-check g-color-gray-dark-v5 g-font-size-13 mb-0 g-pl-25">
                                                {{ form.confirmed(type="checkbox", id="gender1", class='form-check custom-control-input',value="True") }}
                                                <span class="d-block u-check-icon-checkbox-v6 g-absolute-centered--y g-left-0">
                                                    <i class="fa" data-check-icon="&#xF00C;"></i>
                                                </span>
                                            </label>
                                    </div>
                                </div>
                            {% endif %}
                        {# 姓名 & 性别 #}
                            <div class="row mx-5">
                                <div class="col-sm-6 d-flex align-items-center mb-3"><p class="my-0">真实姓名：</p>{{ form.name(class='form-control form-control-sm g-font-size-13 g-max-width-60x') }}</div>
                                <div class="col-sm-6 d-flex align-items-center mb-3">
                                    <p class="my-0">性别：</p>
                                    {{ form.gender(class='form-control form-control-sm g-font-size-13 g-max-width-60x') }}
                                </div>
                            </div>
                        {# 地址 #}
                            <div class="row mx-5 mb-1">
                                <div class="col-12 col-lg-7 d-flex align-items-center mb-3"><p class="my-0">地址：</p>{{ form.location(class='form-control form-control-sm g-font-size-13 g-max-width-60x') }}</div>
                            </div>
                        {# 注册时间 & 上次登录 #}
                            <div class="row mx-5">
                                <div class="col-sm-6"><p>注册时间：{{ user.member_since }}</p></div>
                                <div class="col-sm-6"><p>上次登录：{{ user.last_seen }}</p></div>
                            </div>
                        {# 个人简介 #}
                            <div class="row mx-5 overflow-auto">
                                <div class="col-12 mb-3"><p class=" my-0">个人简介：</p>{{ form.about_me(class='form-control') }}</div>
                            </div>
                        {# 保存按钮 #}
                            <footer class="d-flex justify-content-center mt-2 mb-3">
                                {% if current_user.is_administrator() %}
                                    {{ form.submit(value="保存(管理员)", class="btn btn-lg g-width-50x g-width-30x--md g-color-red g-color-white--hover u-btn-outline-red g-rounded-50") }}
                                {% else %}
                                    {{ form.submit(value="保存", class="btn btn-lg g-width-30x g-color-primary g-color-white--hover u-btn-outline-primary g-rounded-50") }}
                                {% endif %}
                            </footer>
                        </form>
                    </section>
                </div>
            </div>
{% endblock user_page_right_side %}

app/templates/user/my_comments.html
{% extends "user/user_page.html" %}
{% from "_macros.html" import pagination_widget %}

{% block title %}{{ user.username }} - 我的评论{% endblock %}

{% block profile_list %}
    <ul class="list-unstyled">
        <li id="profile" class="d-flex align-items-center g-py-8 g-px-15 u-link-v5 g-color-text g-bg-gray-light-v5--hover g-rounded-7" style="transform: rotate(0);">
            <i class="fa fa-id-card-o g-font-size-22 u-line-icon-pro"></i>
            <a href="{{ url_for('user_page.user', username=user.username) }}"
               class="text-decoration-none g-color-gray-dark-v4 g-color-primary--hover stretched-link">&nbsp; &nbsp;个人资料</a>
        </li>
        <li id="likes" class="d-flex align-items-center g-py-8 g-px-15 u-link-v5 g-color-text g-bg-gray-light-v5--hover g-rounded-7" style="transform: rotate(0);">
            <i class="fa fa-star-o g-font-size-22 u-line-icon-pro"></i>
            <a href="{{ url_for('user_page.my_likes') }}" class="g-ml-5 text-decoration-none g-color-gray-dark-v4 g-color-primary--hover stretched-link">&nbsp; &nbsp;我的收藏</a>
        </li>
        <li id="comments" class="d-flex align-items-center g-py-8 g-px-15 u-link-v5 g-color-text g-bg-gray-light-v5 g-rounded-7" style="transform: rotate(0);">
            <i class="fa fa-commenting-o g-font-size-22 u-line-icon-pro"></i>
            <a href="{{ url_for('user_page.my_comments') }}" class="g-ml-3 text-decoration-none g-color-primary--active stretched-link">&nbsp; &nbsp;我的评论</a>
        </li>
        <li id="replies" class="d-flex align-items-center g-py-8 g-px-15 u-link-v5 g-color-text g-bg-gray-light-v5--hover g-rounded-7" style="transform: rotate(0);">
            <i class="fa fa-comments-o g-font-size-22 u-line-icon-pro"></i>
            <a href="#" class="g-ml-3 text-decoration-none g-color-gray-dark-v4 g-color-primary--hover stretched-link">&nbsp; &nbsp;回复我的</a>
        </li>
    </ul>
{% endblock %}

{% block user_page_right_side %}
    <div class="col-md-8 g-mb-50">
        <div class="border g-bg-white g-brd-gray-light-v4 rounded" style="min-height: 440px">
            <section class="g-color-gray-dark-v4">
                {% for comment in comments %}
                <div class="col-lg-12">
                    <div class="border mt-4 g-rounded-5">
                        <div class="">
                            <div class="social-body g-pb-5 g-rounded-top-5">
                                {{ comment.body_html | safe }}
                            </div>
                            <ul class="list-inline mb-0 g-px-15 g-font-size-12 g-bg-gray-light-v3">
                                <li class="list-inline-item mr-4"><i class="fa fa-sign-in"></i> <a class="g-color-gray-dark-v4 g-color-primary--hover" href="{{ url_for("blog.post", id=comment.post_id) }}" >《{{ comment.post.title }}》</a></li>
                                <li class="list-inline-item mr-4"><i class="fa fa-comments-o"></i> <a>{{ comment.replies.count() }}</a></li>
                                <li class="list-inline-item mr-4"><i class="fa fa-clock-o"></i> <a>{{ moment(comment.timestamp).format('lll') }}</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <div class="my-5 px-5">
                    {{ pagination_widget(pagination, 'user_page.my_comments') }}
                </div>
            </section>
        </div>
    </div>
{% endblock user_page_right_side %}

app/templates/user/my_likes.html
{% extends "user/user_page.html" %}
{% from "_macros.html" import pagination_widget %}

{% block title %}{{ user.username }} - 我的收藏{% endblock %}

{% block profile_list %}
    <ul class="list-unstyled">
        <li id="profile" class="d-flex align-items-center g-py-8 g-px-15 u-link-v5 g-color-text g-bg-gray-light-v5--hover g-rounded-7" style="transform: rotate(0);">
            <i class="fa fa-id-card-o g-font-size-22 u-line-icon-pro"></i>
            <a href="{{ url_for('user_page.user', username=user.username) }}"
               class="text-decoration-none g-color-gray-dark-v4 g-color-primary--hover stretched-link">&nbsp; &nbsp;个人资料</a>
        </li>
        <li id="likes" class="d-flex align-items-center g-py-8 g-px-15 u-link-v5 g-color-text g-bg-gray-light-v5 g-rounded-7" style="transform: rotate(0);">
            <i class="fa fa-star-o g-font-size-22 u-line-icon-pro"></i>
            <a href="{{ url_for('user_page.my_likes') }}" class="g-ml-5 text-decoration-none g-color-primary--active stretched-link">&nbsp; &nbsp;我的收藏</a>
        </li>
        <li id="comments" class="d-flex align-items-center g-py-8 g-px-15 u-link-v5 g-color-text g-bg-gray-light-v5--hover g-rounded-7" style="transform: rotate(0);">
            <i class="fa fa-commenting-o g-font-size-22 u-line-icon-pro"></i>
            <a href="{{ url_for('user_page.my_comments') }}" class="g-ml-3 text-decoration-none g-color-gray-dark-v4 g-color-primary--hover stretched-link">&nbsp; &nbsp;我的评论</a>
        </li>
        <li id="replies" class="d-flex align-items-center g-py-8 g-px-15 u-link-v5 g-color-text g-bg-gray-light-v5--hover g-rounded-7" style="transform: rotate(0);">
            <i class="fa fa-comments-o g-font-size-22 u-line-icon-pro"></i>
            <a href="#" class="g-ml-3 text-decoration-none g-color-gray-dark-v4 g-color-primary--hover stretched-link">&nbsp; &nbsp;回复我的</a>
        </li>
    </ul>
{% endblock %}

{% block user_page_right_side %}
    <div class="col-md-8 g-mb-50">
        <div class="border g-bg-white g-brd-gray-light-v4 rounded" style="min-height: 440px">
            <section class="g-color-gray-dark-v4">
                <div class="col-lg-12">
                    <div class="hr-line-dashed"></div>
                    {% for like in likes %}
                        <div class="row">
                            <div class="col-2 text-center px-0">
                                <div>
                                    <img class="img-fluid g-min-width-40  rounded-circle border g-pa-3" src="{{ like.post.author.avatar }}" style="max-width: 50px;">
                                </div>
                                <div>
                                    <span class="g-font-size-12 g-font-weight-600">{{ like.post.author.username }}</span>
                                </div>
                            </div>
                            <div class="col-10 pl-0">
                                <h5>
                                    <a class="g-color-blue text-decoration-none g-font-weight-600" href="{{ url_for('blog.post', id=like.post.id) }}">{{ like.post.title }}</a>
                                </h5>
                                <p class="g-font-size-12 g-mt-5">{{ like.post.summary }}</p>
                                <ul class="list-inline mb-0 g-px-15 g-font-size-12 g-bg-gray-light-v3">
                                    <li class="list-inline-item mr-4"><i class="fa fa-map-signs"></i> <a data-toggle="tooltip" data-placement="top" title="分类">{{ like.post.category.name }}</a></li>
                                    <li class="list-inline-item mr-4"><i class="fa fa-clock-o"></i> <a data-toggle="tooltip" data-placement="top" title="收藏时间">{{ moment(like.timestamp).format('lll') }}</a></li>
                                    <li class="list-inline-item mr-4"><i class="fa fa-comments-o"></i> <a data-toggle="tooltip" data-placement="top" title="评论数">{{ like.post.comments.count() }}</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                    {% endfor %}
                </div>
                <div class="my-5 px-5">
                    {{ pagination_widget(pagination, 'user_page.my_likes') }}
                </div>
            </section>
        </div>
    </div>
{% endblock user_page_right_side %}

app/templates/user/upload_avatar.html
{% extends "user/user_page.html" %}

{% block title %}{{ user.username }} - 修改头像{% endblock %}

{% block user_page_right_side %}
    <div class="col-md-8 g-mb-50 ">
                <div class="border g-bg-white g-brd-gray-light-v4 rounded" style="min-height: 440px">
                    <section class="g-color-gray-dark-v4">
                        <header class="text-center mt-4 mb-3"><h3>上传头像</h3></header>
                        <div class="card my-4 mx-5 border-0">
                            <div class="row align-self-center">
                                <img src="{{ user.avatar }}" class="img-fluid card-img g-max-height-100x rounded border g-brd-darkblue g-pa-5 mb-2" style="max-width: 240px; ">
{#                                <p class="g-font-weight-600">当前头像</p>#}
                            </div>
                            <div class="row d-flex justify-content-center">
                                <div class="col-md-10 col-lg-8  card-body">
                                    <form method=POST enctype=multipart/form-data action="{{ url_for('user_page.upload_avatar') }}">
                                        <div class="input-group">
                                            <div class="custom-file">
                                                <input type=file class="custom-file-input" id="upload" name=avatar >
                                                <label class="custom-file-label" for="upload">Choose file</label>
                                            </div>
                                            <div class="input-group-append">
                                                <input class="btn btn-outline-secondary" type="submit" value="Submit">
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
{% endblock user_page_right_side %}

app/templates/user/user_page.html
{% extends "base.html" %}

{% block title %}Potato Cookbook - {{ user.username }}{% endblock %}

{% block content %}
<div class="g-py-20 g-py-40--sm g-bg-lightblue-radialgradient-circle">
    <div class="container">
        <div class="row">
            {# left side #}
            {% block user_page_left_side %}
            <div class="col-md-3 g-mb-50">
                <aside class="g-py-30 g-px-10 g-bg-white border g-brd-gray-light-v4 rounded">
                    {# profile image #}
                    <div>
                        <div class="text-center mb-4 g-pos-rel">
                            <img class="img-fluid g-height-120 g-width-120 rounded-circle border g-pa-3 g-mb-10" src="{{ user.avatar }}" alt="">
                            <span class="d-block g-font-size-16 g-font-weight-600">{{ user.username }}</span>
                            {% if current_user == user %}
                            <a href="{{ url_for('user_page.upload_avatar') }}">
                                <span class="u-icon-v3 u-icon-size--xs g-color-white--hover g-bg-primary--hover rounded-circle g-pos-abs g-top-0 g-right-15 g-cursor-pointer" data-toggle="tooltip"
                                data-placement="top" title="修改头像"><i class="fa fa-pencil mt-2"></i></span>
                            </a>
                            {% endif %}
                            <hr>
                        </div>
                    </div>
                    {# profile list #}
                    <div>
                        {% block profile_list %}
                        <ul class="list-unstyled">
                            <li id="profile" class="d-flex align-items-center g-py-8 g-px-15 u-link-v5 g-color-text g-bg-gray-light-v5 g-rounded-7" style="transform: rotate(0);">
                                <i class="fa fa-id-card-o g-font-size-22 u-line-icon-pro"></i>
                                <a href="{{ url_for('user_page.user', username=user.username) }}"
                                   class="text-decoration-none g-color-primary--active stretched-link">&nbsp; &nbsp;个人资料</a>
                            </li>
                            <li id="likes" class="d-flex align-items-center g-py-8 g-px-15 u-link-v5 g-color-text g-bg-gray-light-v5--hover g-rounded-7" style="transform: rotate(0);">
                                <i class="fa fa-star-o g-font-size-22 u-line-icon-pro"></i>
                                <a href="{{ url_for('user_page.my_likes') }}" class="g-ml-5 text-decoration-none g-color-gray-dark-v4 g-color-primary--hover stretched-link">&nbsp; &nbsp;我的收藏</a>
                            </li>
                            <li id="comments" class="d-flex align-items-center g-py-8 g-px-15 u-link-v5 g-color-text g-bg-gray-light-v5--hover g-rounded-7" style="transform: rotate(0);">
                                <i class="fa fa-commenting-o g-font-size-22 u-line-icon-pro"></i>
                                <a href="{{ url_for('user_page.my_comments') }}" class="g-ml-3 text-decoration-none g-color-gray-dark-v4 g-color-primary--hover stretched-link">&nbsp; &nbsp;我的评论</a>
                            </li>
                            <li id="replies" class="d-flex align-items-center g-py-8 g-px-15 u-link-v5 g-color-text g-bg-gray-light-v5--hover g-rounded-7" style="transform: rotate(0);">
                                <i class="fa fa-comments-o g-font-size-22 u-line-icon-pro"></i>
                                <a href="#" class="g-ml-3 text-decoration-none g-color-gray-dark-v4 g-color-primary--hover stretched-link">&nbsp; &nbsp;回复我的</a>
                            </li>
                        </ul>
                        {% endblock %}
                    </div>
                </aside>
            </div>
            {% endblock %}
            {# right side #}
            {% block user_page_right_side %}
            <div class="col-md-8 g-mb-50 ">
                <div class="border g-bg-white g-brd-gray-light-v4 rounded" style="min-height: 440px">
                    <section class="g-color-gray-dark-v4" id="user_profile" >
                        <header class="text-center mt-4 mb-3"><h3>我的资料</h3></header>
                        <hr class="mx-5">
                        <div>
                            <div class="row mx-5">
                            <div class="col-sm-6"><p>用户名：{{ user.username }}</p></div>
                            <div class="col-sm-6"><p>邮箱：{{ user.email }}</p></div>
                        </div>
                            <div class="row mx-5">
                                <div class="col-sm-6"><p>真实姓名：{% if user.name %}  {{ user.name }}
                                    {% else %} {% if not current_user.is_administrator() %} <a href="{{ url_for('user_page.edit_profile') }}" class="g-color-primary--hover"><span><i class="fa fa-pencil-square-o"></i>马上填写</span></a> {% endif %}{% endif %}</p></div>
                                <div class="col-sm-6"><p>性别：{{ '男' if user.gender else '女' }}</p></div>
                            </div>
                            <div class="row mx-5">
                                <div class="col-12"><p>地址：{% if user.location %} {{ user.location }}
                                    {% else %} {% if not current_user.is_administrator() %}<a href="{{ url_for('user_page.edit_profile') }}" class="g-color-primary--hover"><span><i class="fa fa-pencil-square-o g-color-primary--hover"></i>马上填写</span></a>{% endif %} {% endif %}</p></div>
                            </div>
                            <div class="row mx-5">
                                <div class="col-sm-6"><p>注册时间：{{ user.member_since }}</p></div>
                                <div class="col-sm-6"><p>上次登录：{{ user.last_seen }}</p></div>
                            </div>
                            <div class="row mx-5 overflow-auto" style="max-height: 87px">
                                <div class="col-12"><p>个人简介：{% if user.about_me %} {{ user.about_me }}
                                    {% else %}你还没有填写个人简介诶 -_-||&nbsp;&nbsp; {% if not current_user.is_administrator() %}<a href="{{ url_for('user_page.edit_profile') }}" class="g-color-primary--hover"><span><i class="fa fa-pencil-square-o"></i>马上填写</span></a> {% endif %}{% endif %}</p></div>
                            </div>
                        </div>
                        <footer class="d-flex justify-content-center mt-4 mb-5 ">
                            {% if current_user.is_administrator() %}
                            <a href="{{ url_for('user_page.edit_profile_admin', id=user.id) }}" class="btn btn-xl g-color-red g-color-white--hover u-btn-outline-red u-btn-hover-v2-2 g-rounded-50" role="button" >
                                <span> &nbsp;编辑个人资料(管理员) <i class="fa fa-edit g-font-size-24 float-left"></i></span>
                            </a>
                            {% elif user == current_user %}
                            <a href="{{ url_for('user_page.edit_profile') }}" class="btn btn-xl g-color-primary g-color-white--hover u-btn-outline-primary u-btn-hover-v2-2 g-rounded-50" role="button" >
                                <span> &nbsp;编辑个人资料 <i class="fa fa-edit g-font-size-24 float-left"></i></span>
                            </a>
                            {% endif %}
                        </footer>
                    </section>
                </div>
            </div>
            {% endblock %}
        </div>
    </div>
</div>
{% endblock content %}